DROP FUNCTION IF EXISTS _timeudb_internal.block_new_chunks;
DROP FUNCTION IF EXISTS _timeudb_internal.allow_new_chunks;
DROP FUNCTION IF EXISTS _timeudb_internal.refresh_continuous_aggregate;
DROP FUNCTION IF EXISTS _timeudb_internal.create_chunk_table;
DROP FUNCTION IF EXISTS _timeudb_internal.create_chunk_replica_table;
DROP FUNCTION IF EXISTS _timeudb_internal.chunk_drop_replica;
DROP FUNCTION IF EXISTS _timeudb_internal.create_chunk;
DROP PROCEDURE IF EXISTS _timeudb_internal.wait_subscription_sync;
DROP PROCEDURE IF EXISTS timeudb_experimental.move_chunk;
DROP PROCEDURE IF EXISTS timeudb_experimental.copy_chunk;
DROP PROCEDURE IF EXISTS timeudb_experimental.cleanup_copy_chunk_operation;
DROP TABLE IF EXISTS _timeudb_catalog.chunk_copy_operation;
DROP SEQUENCE IF EXISTS _timeudb_catalog.chunk_copy_operation_id_seq;
DROP VIEW IF EXISTS timeudb_experimental.chunk_replication_status;
DROP SCHEMA IF EXISTS timeudb_experimental CASCADE;
